version: "3.4"

services:
  postgres:
    image: postgres:latest
    container_name: threads-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # threads:
  #   image: threads:latest
  #   container_name: threads-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  #     THREADS_PORT: 8000
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
    driver: local